### PR TITLE
Adding operator installation playbook for running distributed TensorFlow workloads on the GPU

### PR DESCRIPTION
**Pull request by courtneypacheco**
The contents of my blog artifact folder describe how to install NFD, SRO, and Kubeflow (via Open Data Hub) via my operator installation playbook. There is a `USAGE.md` guide on how to use the playbook, and then there is the playbook itself.

### CODE REVIEW

**Comment by zvonkok** [comment]
@cep235 You could also add g4 instances to the vars. Otherwise 

/lgtm

**Comment by courtneypacheco** [comment]
Thanks. Just added g4 instances to the vars.

**Comment by courtneypacheco** [comment]
Just realized I should probably elaborate on how my playbook uses AWS-specific GPU check, and how to turn off those checks if not using AWS.

**Comment by courtneypacheco** [comment]
I'm actually going to ignore this pull request. Eduardo combined my work into the `ci-artifacts` repo here: https://github.com/openshift-psap/ci-artifacts

**Pull request closed without merging**
